spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        enabled: true
  redis:
    host: redis
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  zipkin:
    base-url: http://zipkin:9411/
    sleuth:
      sampler:
        #采样率值介于 0 到 1 之间，1 则表示全部采集
        probability: 1
        rate: 10
rocketmq:
  name-server: rmqnamesrv:9876 # 访问地址
  producer:
    group: broker-a # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2

elasticsearch:
  host: elasticsearch
  port: 9200
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500

logging:
  level:
    org:
      springframework:
        web: DEBUG