spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

#rocketmq
rocketmq:
  name-server: 127.0.0.1:9876 # 访问地址
  producer:
    group: broker-a # 必须指定group
    send-message-timeout: 10000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2

#es
elasticsearch:
  host: localhost
  port: 9200
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500


#日志
logging:
  level:
    org:
      springframework:
        web: DEBUG